##This function generates a probability table from table generated by SF_sort.
##It can generate a probability table for any data frame in a similar form.  
require(reshape2)
SF_Prob <- function(train, 
                    vars = c("Month", "Year", "DayOfWeek", 
                             "PdDistrict"),
                    dir = "./Output/", 
                    save_as = "prob_table",
                    export = FALSE, 
                    cat_var = "Category") {
    
    ##creates a column with totals count for all categories by variables
    cols <- ncol(train)
    beg <- length(vars)+1
    train$sums <- rowSums(train[, beg:cols])
    
    ## uses the sums column to create probabilities for all categories
    ##based on variables
    train[,beg:cols] <- train[,beg:cols]/train$sums

    ##  removes the sum column
    prob_table<- train[,-(cols+1)]
    ## Table for use
    prob_table <- reshape2::melt(prob_table, vars,
                       value.name = "Prob")
    ## Reduce table to just highest porbability for given variables
    fml <- paste(vars, collapse = "+")
    fml <- paste(fml, "~.", sep = "")
    fml <- as.formula(fml)
    prob <- suppressWarnings(
        suppressMessages(
            reshape2::dcast(prob_table, fml, 
                                             fun.aggregate = max,
                        value.var = "Prob")))
    colnames(prob) <- c(colnames(prob)[1:length(vars)],
                              "Prob")
    ## Add back on Crime category
    prob_table <- left_join(prob, prob_table)
    ## Clean up Colnames
    colnames(prob_table) <- c(colnames(prob_table)[1:length(vars)],
                        "Prob", cat_var)
    ## Because some crimes have the same probability, so reducing
    prob_table <- prob_table[!duplicated(prob_table[,1:length(vars)]),]
    ##writes the file if requested
    if(export){
        save_loc <- paste(dir, save_as, ".csv", sep = "")
        write.csv(prob_table, save_loc, row.names = FALSE)
    }
    
    return(prob_table)         
}
 
