##This function generates a probability table from table generated by SF_sort.
##It can generate a probability table for any data frame in a similar form.  

SF_Prob <- function(file_name = "sort_df", dir = "./", 
                    save_as = "prob_table", beg = 5 ) {
    ##check to make sure file or data frame exist
    file_loc <- paste (dir, file_name, sep ="")
    if (exists(file_name)) {
        test <<- get(file_name)
    } 
    else if (file.exists(file_loc)){
        test <<- read.csv(file_loc, check.names = F)
    }
    
    else { print("file does not exist"); stop }
    

    ##creates a column with totals count for all categories by variables
    for (i in 1:nrow(test)) {
        cols <- ncol(test)
        
        test$sums[i] <- sum(test[i, beg:cols]) 
    }
    
    ## uses the sums column to create probabilities for all categories
    ##based on variables
    prob_table <- as.data.frame(NULL)
    for (i in 1:nrow(test)) {
        for(h in 1:ncol(test)) {
            if (h < beg) {
                prob_table[i, h] <- test[i, h]
            }else if(class(test[i,h]) == "integer") {
                prob_table[i, h] <- test[i,h]/test[i, "sums"]
            }else {warning("Issue with column ", h, " and row ", i )}
        }
    }
    ## Puts bakc in column names, removes the sum column, and writes the file
    names(prob_table) <- names(test)
    prob_table[,"sums"] <- NULL

    save_loc <- paste(dir, save_as, ".csv", sep = "")
    write.csv(prob_table, save_loc)
    prob_table <<- prob_table         
}
 